# Generated by Django 5.0.7 on 2024-07-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crianca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_crianca", models.CharField(max_length=100)),
                ("idade_crianca", models.IntegerField()),
                ("nome_mae", models.CharField(max_length=100)),
                ("vacina", models.CharField(max_length=100)),
            ],
        ),
    ]
