# Generated by Django 5.0.7 on 2024-07-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacinacao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crianca",
            name="bairro",
            field=models.CharField(default="-", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="crianca",
            name="vacina",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
